apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-delivery-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youcan_backend
  template:
    metadata:
      labels:
        app: youcan_backend
        tier: analytics-delivery-deployment
    spec:
      containers:
      - name: analytics-delivery-deployment
        image: 034363173241.dkr.ecr.us-east-1.amazonaws.com/analytics_delivery:0.0.1
        args:
        - ./scripts/Entrypoint.sh
        env:
        - name: AMQP_URL
          value: rabbitmq-service:8081