apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youcan_backend
  template:
    metadata:
      labels:
        app: youcan_backend
        tier: userservice-deployment
    spec:
      containers:
      - name: userservice-deployment
        image: 034363173241.dkr.ecr.us-east-1.amazonaws.com/user:1.1.2
        args:
        - ./scripts/Entrypoint.sh
        env:
        - name: AMQP_URL
          value: rabbitmq-service:8081