apiVersion: v1
kind: Service
metadata:
  name: testinguserservice
spec:
  type: ClusterIP
  selector:
    app: youcan_backend
    tier: testinguserservice
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080