apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testingpushnotification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youcan_backend
  template:
    metadata:
      labels:
        app: youcan_backend
        tier: testingpushnotification
    spec:
      containers:
      - name: testingpushnotification
        image: 034363173241.dkr.ecr.us-east-1.amazonaws.com/push-notification:1.0.0
        args:
        - ./scripts/Entrypoint.sh
        env:
        - name: AMQP_URL
          value: rabbitmq-service:8081
        - name: database_host
          value: "youcav-db.cnfabpkcjfhv.us-east-1.rds.amazonaws.com"
        - name: database_password
          value: Qwerty12
        - name: schema
          value: userservice
        - name : connection
          value : mongodb://Administrator:Qwerty12#$$@youcan-cluster-shard-00-00-ms4fp.gcp.mongodb.net:27017,youcan-cluster-shard-00-01-ms4fp.gcp.mongodb.net:27017,youcan-cluster-shard-00-02-ms4fp.gcp.mongodb.net:27017/OAUTH?ssl=true&replicaSet=Youcan-Cluster-shard-0&authSource=admin